# Generated by Django 5.2.7 on 2025-10-07 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='created_at',
            new_name='package_created_at',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='description',
            new_name='package_description',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='features',
            new_name='package_features',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='images',
            new_name='package_images',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='package_name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='price',
            new_name='package_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='updated_at',
            new_name='package_updated_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='category',
            new_name='shop_category',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='created_at',
            new_name='shop_created_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='description',
            new_name='shop_description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='images',
            new_name='shop_images',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='is_active',
            new_name='shop_is_active',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='price',
            new_name='shop_price',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='publish_date',
            new_name='shop_publish_date',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='updated_at',
            new_name='shop_updated_at',
        ),
    ]
