# Generated by Django 5.2.7 on 2025-10-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_created_at_package_package_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_features',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_publish_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop_updated_at',
            new_name='updated_at',
        ),
    ]
