# Generated by Django 5.2.7 on 2025-10-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_package_stock_shop_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
