# Generated by Django 5.2.7 on 2025-10-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('pending', 'Pending')], default='progress', max_length=12),
        ),
    ]
