# Generated by Django 5.2.7 on 2025-10-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('progress', 'Progress'), ('complete', 'Complete')], default='progress', max_length=12),
        ),
    ]
