# Generated by Django 5.2.7 on 2025-10-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='shops',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
