# Generated by Django 5.2.7 on 2025-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_date_booking_print_name_booking_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
