# Generated by Django 5.2.7 on 2025-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
