# Generated by Django 5.2.7 on 2025-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('progress', 'Progress'), ('rent started', 'Rent Started'), ('completed', 'Completed')], default='progress', max_length=12),
        ),
    ]
