# Generated by Django 5.2.7 on 2025-10-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('progress', 'Progress'), ('confirm', 'Confirm'), ('completed', 'Completed')], default='progress', max_length=12),
        ),
    ]
