# Generated by Django 5.2.7 on 2025-10-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.CharField(max_length=100),
        ),
    ]
