# Generated by Django 5.2.7 on 2025-10-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_couponemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('promotion', 'Promotion'), ('coupon', 'Coupon'), ('event', 'Event'), ('reminder', 'Reminder'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('body_html', models.TextField(help_text='You can use HTML here for formatting.')),
                ('body_text', models.TextField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='couponemaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.emailtemplate'),
        ),
    ]
