# Generated by Django 5.2.7 on 2025-10-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_emailtemplate_couponemaillog_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(),
        ),
    ]
